

# !!! МАШИНА = МАЙНИНГ-ФЕРМА (памятка для понимания)

machines: # настройки машин (вы можете добавлять новые машины, главное чтобы их айди не повторялись!)
  machine-1: # id машины
    name: "&#BBFFF2Железная майнинг-ферма" # имя машины (предмета)
    lore: # лор машины (предмета), многострочный
      - "&7[Бюджетная модель]"
    material: IRON_BLOCK # материал машины (ОБЯЗАТЕЛЬНО блок)
    glow: true # должен ли предмет машины иметь эффект свечения?
    lighting-color: WHITE # цвет подсветки блока машины (none - убрать подсветку)
    # ВАЖНО!!! Не включайте подсветку, если материал машины - НЕ ПОЛЫЙ БЛОК
    # Например, сундук или ступенька - НЕ ВКЛЮЧАТЬ
    # Железный блок, блок земли - МОЖНО ВКЛЮЧАТЬ
    income: 10 # базовая прибыль машины в секунду (без видеокарт)
    gpu-amount: 6 # сколько видеокарт вмещает в себя машина

  machine-2: # вторая машина, машин может быть сколько угодно
    name: "&#FFBF00Золотая майнинг-ферма"
    lore:
      - "&7[Дорогая модель]"
    material: GOLD_BLOCK
    glow: true
    lighting-color: YELLOW
    income: 10
    gpu-amount: 12


video-cards: # настройки видеокарт (вы можете добавлять новые видеокарты, главное чтобы их айди не повторялись!)
  gpu-1: # id видеокарты
    name: "&fВидеокарта &7[&cRX580&7]" # имя видеокарты (предмета)
    lore: # лор видеокарты (многострочный)
      - "&fЧтобы вставить видеокарту"
      - "&aКликните &fею по ферме!"
    material: IRON_INGOT # материал видеокарты (любой, если это будет материал блока, то в плагине есть защита, игроки не смогут их ставить)
    glow: true # должен ли светится предмет видеокарты
    profit-margin: 20 # надбавка к прибыли, при установке в машину (прибыль стакается)

  gpu-2: # вторая видеокарта, видеокарт может быть сколько угодно
    name: "&fВидеокарта &7[&aRTX4060&7]"
    lore:
      - "&fЧтобы вставить видеокарту"
      - "&aКликните &fею по ферме!"
    material: NETHERITE_INGOT
    glow: true
    profit-margin: 40


destroy-piston: true # должен ли поршень ломаться, при попытке сдвинуть машину (false - обычная блокировка поршня при попытке двинуть машину)
anti-explode: true # должны ли машины быть защищены от взрывов?
strict-ownership: true # если true - то зайти в меню машины и пользоваться ею сможет лишь ВЛАДЕЛЕЦ (тот, кто изначально установил машину)


command-give-balance: "eco give {player} {balance}" # ваша команда для выдачи валюты игроку
# {balance} - заменится баланс, накопившийся в машине
# {player} - заменится на ник игрока
# с помощью данной настройки вы сможете подключить любой плагин экономики
# с поддержкой кастомной валюты


db-save-interval: 5 # как часто плагин будет сохранять некоторые изменения по балансам машин в БД
# независимо от этого, плагин записывает в базу данных некоторые действия, например установка или
# поломка машин, установка видеокарт и прочее. Но так как баланс в машинах обновляется каждую секунду,
# то данные, связанные с балансом, сохраняются интервально
# Если ваш сервер стабилен, то можете выставлять высокие значения
# !!! В МИНУТАХ !!!